### PR TITLE
Adding action workflow

### PR DESCRIPTION
**Pull request by artis3n**

### CODE REVIEW

**Comment by artis3n** [comment]
Action correctly failed without a review.

**Comment by artis3n-testuser** [comment]
Manually re-triggering action

**Comment by artis3n** [comment]
Passed. Now adding a new commit...

**Comment by artis3n** [comment]
It passed (https://github.com/artis3n/signoff-new-commit-test/commit/661bcc5ab5e6b460c0231cd8b84a1f94289c63fe/checks?check_suite_id=396647308) but didn't update this pull request. Maybe because I added the new type mid-review. Closing and re-submitting.

**Pull request closed without merging**
